#!/usr/bin/env bash
set -euo pipefail

LOGIN_ENV="$(su -l "$DISTROBOX_USER" -c 'printenv')"
env_get() {
  printf '%s\n' "${LOGIN_ENV}" | awk -F= -v key="$1" '$1==key{print substr($0,length(key)+2)}'
}

OVERLAY_ROOT="/var/lib/tool-overlay"

XDG_DATA_HOME="$(env_get XDG_DATA_HOME)"
XDG_DATA_HOME="${XDG_DATA_HOME:-$DISTROBOX_USER_HOME/.local/share}"
XDG_CONFIG_HOME="$(env_get XDG_CONFIG_HOME)"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$DISTROBOX_USER_HOME/.config}"
XDG_CACHE_HOME="$(env_get XDG_CACHE_HOME)"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$DISTROBOX_USER_HOME/.cache}"
XDG_STATE_HOME="$(env_get XDG_STATE_HOME)"
XDG_STATE_HOME="${XDG_STATE_HOME:-$DISTROBOX_USER_HOME/.local/state}"

###
MISE_CONFIG_DIR="${XDG_CONFIG_HOME}/mise"
MISE_CACHE_DIR="${XDG_CACHE_HOME}/mise"
MISE_STATE_DIR="${XDG_STATE_HOME}/mise"
MISE_DATA_DIR="${XDG_DATA_HOME}/mise"

OVERLAY_MISE_CONFIG_DIR="${OVERLAY_ROOT}/mise-config"
OVERLAY_MISE_CACHE_DIR="${OVERLAY_ROOT}/mise-cache"
OVERLAY_MISE_STATE_DIR="${OVERLAY_ROOT}/mise-state"
OVERLAY_MISE_DATA_DIR="${OVERLAY_ROOT}/mise-data"
###

USER_UID=$(id -ru ${DISTROBOX_USER})
USER_GID=$(id -rg ${DISTROBOX_USER})

mkdir -p \
 ${MISE_CONFIG_DIR} \
 ${MISE_CACHE_DIR} \
 ${MISE_STATE_DIR} \
 ${MISE_DATA_DIR} \
 ${OVERLAY_MISE_CONFIG_DIR} \
 ${OVERLAY_MISE_CACHE_DIR} \
 ${OVERLAY_MISE_STATE_DIR} \
 ${OVERLAY_MISE_DATA_DIR} \
;

chown "${USER_UID}:${USER_GID}" \
 ${MISE_CONFIG_DIR} \
 ${MISE_CACHE_DIR} \
 ${MISE_STATE_DIR} \
 ${MISE_DATA_DIR} \
 ${OVERLAY_MISE_CONFIG_DIR} \
 ${OVERLAY_MISE_CACHE_DIR} \
 ${OVERLAY_MISE_STATE_DIR} \
 ${OVERLAY_MISE_DATA_DIR} \
;

mount --bind ${MISE_CONFIG_DIR} ${OVERLAY_MISE_CONFIG_DIR}
mount --bind ${MISE_CACHE_DIR} ${OVERLAY_MISE_CACHE_DIR}
mount --bind ${MISE_STATE_DIR} ${OVERLAY_MISE_STATE_DIR}
mount --bind ${MISE_DATA_DIR} ${OVERLAY_MISE_DATA_DIR}
